[package]
name = "highnoon"
version = "0.1.0"
authors = ["Steve Lee <sphen.lee@gmail.com>"]
edition = "2018"

description = "minimal web server framework inspired by tide, but built on hyper"
license = "MIT"
repository = "https://github.com/sphenlee/highnoon"
documentation = "https://docs.rs/highnoon"
readme = "README.md"

keywords = ["web", "tokio", "hyper", "http"]
categories = ["web-programming::http-server"]

[dependencies]
hyper = "0.13"
route-recognizer = "0.3"
async-trait = "0.1"
hyperx = "1.1.0"
serde = "1.0"
serde_json = "1.0"
serde_urlencoded = "0.7"
thiserror = "1"


[dev-dependencies]
tokio = { version = "0.2", features = ["rt-threaded", "net", "macros"] }
